[[capabilities]]
== iSchedule Receiver Capabilities

iSchedule Receivers supporting the features described in this document MUST allow
iSchedule Senders to query their capabilities by accepting GET requests targeted at
the Request-URI found during discovery (<<discovery>>). The response body for a
successful GET request targeted at this URI MUST be an XML document with
IS:query-result as its root element.

[NOTE]
====
Informative rationale: The GET method was favored over the POST method to allow
iSchedule Senders to query capabilities with "conditional GET" requests (see
<<RFC7232>>).
====

iSchedule Receivers SHOULD use normal HTTP expiration mechanisms (as per
<<RFC7234,section=5.2>>) to ensure caches do not cache the capabilities response for
too long. iSchedule Senders SHOULD use normal HTTP conditional GET requests when
re-checking capabilities to avoid re-transferring already cached data.

iSchedule Senders SHOULD use the information in the capabilities to determine
whether the iSchedule Receiver supports a version of the protocol that the iSchedule
Sender can use, and if not, not issue any iSchedule requests with scheduling
messages to the iSchedule Receiver. iSchedule Senders SHOULD verify that the
scheduling message to be sent to the iSchedule Receiver is in line with the
restrictions on scheduling messages indicated by the capabilities before sending the
scheduling message.

[[ISCHEDULE_RECEIVER_CAPABILITIES_EXAMPLE]]
=== Example: Querying iSchedule Receiver Capabilities

.>> Request <<
[source%unnumbered]
----
GET /.well-known/ischedule?action=capabilities HTTP/1.1
Host: cal.example.com
----

.>> Response <<
[source%unnumbered]
----
HTTP/1.1 200 OK
Date: Mon, 15 Dec 2008 09:32:12 GMT
Content-Type: application/xml; charset=utf-8
Content-Length: xxxx
iSchedule-Version: 1.0
iSchedule-Capabilities: 123
ETag: "afasdf-132afds"

<?xml version="1.0" encoding="utf-8" ?>
<query-result xmlns="urn:ietf:params:xml:ns:ischedule">
  <capabilities>
    <serial-number>123</serial-number>
    <versions>
      <version>1.0</version>
    </versions>
    <scheduling-messages>
      <component name="VEVENT">
        <method name="REQUEST"/>
        <method name="ADD"/>
        <method name="REPLY"/>
        <method name="CANCEL"/>
      </component>
      <component name="VTODO">
        <method name="REQUEST"/>
        <method name="ADD"/>
        <method name="REPLY"/>
        <method name="CANCEL"/>
      </component>
      <component name="VFREEBUSY">
        <method name="REQUEST"/>
      </component>
    </scheduling-messages>
    <calendar-data-types>
      <calendar-data-type
       content-type="text/calendar" version="2.0"/>
    </calendar-data-types>
    <attachments>
      <inline/>
      <external/>
    </attachments>
    <rscales>
      <rscale>GREGORIAN</rscale>
      <rscale>CHINESE</rscale>
    </rscales>
    <max-content-length>102400</max-content-length>
    <min-date-time>19910101T000000Z</min-date-time>
    <max-date-time>20381231T000000Z</max-date-time>
    <max-instances>150</max-instances>
    <max-recipients>250</max-recipients>
    <administrator>mailto:ischedule-admin@example.com</administrator>
  </capabilities>
</query-result>
----
