[[introduction]]
== Introduction

This binding document provides the transport specific information necessary to
convey iCalendar Transport-independent Interoperability Protocol (iTIP)
<<RFC5546>> messages over the Hypertext Transfer Protocol (HTTP) <<RFC7230>>.

The Internet Calendar Scheduling Protocol (iSchedule) enables interoperability
between different calendaring and scheduling systems. Calendaring and scheduling
systems that provide support for iSchedule allow their users to perform
scheduling transactions such as schedule, reschedule, respond to scheduling
request or cancel scheduled calendar components, as well as search for busy time
information with users of other calendaring and scheduling systems on the
Internet.

Discussion of this Internet-Draft is taking place on the mailing list
<https://www.ietf.org/mailman/listinfo/ischedule>.

=== Motivations

The iCalendar Message-Based Interoperability Protocol (iMIP) <<RFC6047>>, has
proven to be insufficient to allow users to seamlessly perform the same
scheduling operations with users of other calendaring and scheduling systems on
the Internet as with users of their own system. This section clarifies the
motivations for a binding from the iCalendar Transport-independent
Interoperability Protocol (iTIP) <<RFC5546>> to a transport that allows
synchronous end-to-end connectivity.

A binding to an email-based transport is clearly inadequate to search for busy
time information since users need and expect to get an immediate response. As
such, some calendaring and scheduling systems allow users to publish their free
busy information in a resource accessible to others on the Internet. In the
absence of a standardized mechanism to locate the resource that provides the
free busy information of a user, one thus needs to know the location of this
resource in addition to the calendar user address of the users one wishes to
schedule with.

With an email-based transport, the transparent processing of incoming scheduling
messages on the server is only possible when the calendaring and scheduling
system is integrated with the email system. Commonly, the processing of incoming
scheduling messages occurs on the client and requires user intervention, which
yields the following consequences:

. The processing of incoming scheduling messages and the corresponding updates
to the calendar only occur when the client is active. As a result, free busy
information may be inaccurate (e.g., user still appears busy when the organizer
actually rescheduled or canceled the meeting).

. Calendaring and scheduling systems generally restrain the number of updates
sent to users to reduce the number of messages that will clutter their email
inbox. As a result, attendees rarely obtain up to date participation status of
other attendees.

. The client becomes responsible for verification of the authenticity and
integrity of the scheduling message.

=== Related Memos

Implementers will need to be familiar with other documents that, along with this
document, form a framework for Internet calendaring and scheduling standards.

This document specifies a binding from iTIP to HTTP.

* <<RFC5545,iCalendar>> specifies a core specification of objects, data types,
properties and property parameters;

* <<RFC5546,iTIP>> specifies an interoperability protocol for scheduling between
different implementations.

This document does not attempt to repeat the specification of concepts or
definitions from these other documents. Where possible, references are made to
the document that provides the specification of these concepts or definitions.

=== Terminology

This specification reuses much of the same terminology as <<RFC5545,iCalendar>>,
<<RFC5546,iTIP>>, and <<RFC7230,HTTP>>. Additional terms used by this
specification are:

Scheduling message:: An <<RFC5545,iCalendar>> object conforming to the
requirements of <<RFC5546,iTIP>>.

Originator:: The calendar user who is sending a scheduling message to one or
more other calendar users.

Recipient:: A calendar user to whom a scheduling message is being sent.

iSchedule Sender:: The iSchedule service responsible for sending scheduling
messages.

iSchedule Receiver:: The iSchedule service responsible for receiving scheduling
messages.

=== Notational Conventions

The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT", "SHOULD",
"SHOULD NOT", "RECOMMENDED", "MAY", and "OPTIONAL" in this document are to be
interpreted as described in <<RFC2119>>.

The Augmented BNF (ABNF) syntax used by this document to describe protocol
elements is defined in <<RFC5234>>.

Definitions of XML elements in this document use XML element type declarations
(as found in XML Document Type Declarations), described in Section 3.2 of
<<W3C.REC-xml-20081126>>.

The namespace "urn:ietf:params:xml:ns:ischedule" is reserved for the XML
elements defined in this specification, or in other Standards Track IETF RFCs
written to extend iSchedule. It MUST NOT be used for proprietary extensions.
When XML element types in this namespace are referenced in this document outside
of the context of an XML fragment, the string "IS:" will be prefixed to the
element type names.

Note that the XML declarations used in this document are incomplete, in that
they do not include namespace information. Thus, the reader MUST NOT use these
declarations as the only way to validate iSchedule XML element types.
